### ISSUE TITLE
[bug] control panel checkboxes are unchecked after page refresh/next question

### ISSUE THREAD

**Issue by WiktorJanecki** [MrCyjaneK/testportal-multitool#1]
I found this really small bug with page refreshing.
When question changes (witch forces page refresh) or you manually refresh the page two of checkboxes (**Hacker mode and ***** *****) uncheck.

Photo:
![image](https://user-images.githubusercontent.com/48865169/100604235-89d21900-3306-11eb-94b4-fe119d9eefe4.png)

**Comment by MrCyjaneK** [comment]
I've fixed it at some point..
