### ISSUE TITLE
images missing

### ISSUE THREAD

**Issue by Arheont** [MrCyjaneK/testportal-multitool#5]
It looks like script prevents some of the images from loading (ussualy second and 4) .

J recordeed it :

https://youtu.be/00RkNPIEJXY

**Comment by MrCyjaneK** [comment]
this is an insanely old version. Please try the latest one: https://mrcyjanek.net/projects/testportal-multitool/

**Comment by Arheont** [comment]
Unfortunetly installing version 1.2.16 didnt fix it. J use google chrome and Tampermonkey plug in.

**Comment by MrCyjaneK** [comment]
I'll take look at it tonight
