### ISSUE TITLE
Testportal bar is floating in the middle of the screen.

### ISSUE THREAD

**Issue by m1chaelbarry** [MrCyjaneK/testportal-multitool#7]
I figured out it can be blocked with ublock origin picker, but i think it can be done inside the script

here is filter from ublock
> ``www.testportal.pl##.header-test-wrap``

![issue](https://user-images.githubusercontent.com/69900794/151137451-e90e25ea-8b3a-439c-9b10-9d660ece1b4e.png)

**Comment by MrCyjaneK** [comment]
Will take care of that, thanks

**Comment by MrCyjaneK** [comment]
fixed
