### ISSUE TITLE
Certain pages not loading in.

### ISSUE THREAD

**Issue by TheKacperu** [MrCyjaneK/testportal-multitool#8]
For example, while trying to access page brainly.pl it refuses connection
![pogers](https://user-images.githubusercontent.com/99011232/152496295-658977b8-d6f1-4bff-8564-1e8df687b45c.png)
Is it possible to fix it?

**Comment by MrCyjaneK** [comment]
Yes, the fix will come this weekend

**Comment by MrCyjaneK** [comment]
fixed
